version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: k@123
      POSTGRES_DB: keshav
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - network

  your-application:
    build:
      context: ./java-project
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - network

volumes:
  postgres-data:

networks:
  network:
